phenopacketlab:
  # Path to folder with data files prepared by running `phenopacketlab-ingest ingest`
  data-directory:
  # Disease databases to use
  #disease-databases: ['OMIM', 'ORPHANET', 'DECIPHER']
  # Numer of threads used to load resources during startup.
  loader-threads: 4
  # Keep track of used Phenopacket Schema artifact.
  phenopacket-schema-version: @phenopacket.version@
  text-mining:
    # Choose the text mining provider (just `FENOMINAL` for now).
    provider: 'FENOMINAL'

api:
  version: /api/v1

spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: phenopacketlab
