phenopacketlab:
  # Path to folder with data files prepared by running `phenopacketlab-ingest ingest`
  data-directory:
  # Disease databases to use
  #disease-databases: ['OMIM', 'ORPHANET', 'DECIPHER']
  # Numer of threads used to load resources during startup.
  loader-threads: 4
  # Keep track of used Phenopacket Schema artifact.
  phenopacket-schema-version: @phenopacket.version@
  text-mining:
    # Choose the text mining provider (just `FENOMINAL` for now).
    provider: 'FENOMINAL'
  # Set vocabularies for using as disease concepts.
  disease-database-prefixes:
    - 'MONDO'
    - 'OMIM'
    - 'ORPHA'
    # - 'DECIPHER'
  # Set vocabularies for using as phenotype features.
  phenotype-prefixes:
    - 'HP'
  # Set vocabularies for using as chemical entity concepts.
  chemical-entity-prefixes:
    - 'CHEBI'

api:
  version: /api

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://thejacksonlaboratory.auth0.com/
  cloud:
    gcp:
      datastore:
        project-id: jax-robinson-phenopacket
        credentials:
          scopes: https://www.googleapis.com/auth/datastore
        namespace: dev
auth0:
  audience: "https://phenopacketlab.jax.org"