phenopacketlab:
  # Path to folder with data files prepared by running `phenopacketlab-ingest ingest`
  data-directory:
  # Disease databases to use
  #disease-databases: ['OMIM', 'ORPHANET', 'DECIPHER']
  # Numer of threads used to load resources during startup.
  loader-threads: 4
  # Keep track of used Phenopacket Schema artifact.
  phenopacket-schema-version: @phenopacket.version@
  text-mining:
    # Choose the text mining provider (just `FENOMINAL` for now).
    provider: 'FENOMINAL'

api:
  version: /api

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://thejacksonlaboratory.auth0.com/
  data:
    mongodb:
      host: localhost
      port: 27017
      database: phenopacketlab
auth0:
  audience: "https://phenopacketlab.jax.org"