# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: SQA Backend CI/CD

on:
  push:
    branches: [ SQA ]

jobs:
  build-test-backend:
    runs-on: ${{ matrix.os }}
    env:
      JDK_VERSION: ${{ matrix.jdk }}

    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest ]
        jdk: [ 17 ]

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Build with Maven
        run: ./mvnw --projects phenopacketlab-restapi --also-make --batch-mode verify

  deploy-backend:
    needs: [build-test-backend]
    name: Setup, Build Docker Img, Publish, and Deploy to Cloud Run
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      # build backend
      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Build Backend with Maven
        run: ./mvnw -DskipTests package

      # Setup gcloud CLI
      - uses: google-github-actions/setup-gcloud@v0
        with:
          service_account_email: ${{ secrets.SA_EMAIL }}
          service_account_key: ${{ secrets.GCP_CREDENTIAL }}
          project_id: ${{ secrets.GCP_PROJECT }}
          export_default_credentials: true

      # Download the data folder locally
      - name: Get_data
        run: gsutil cp -r gs://jax-robinson-phenopacket-project-data/data .

      # Build docker image
      - name: Image_build
        run: docker build -t us-docker.pkg.dev/jax-cs-registry/docker/${{ secrets.GCP_PROJECT }}/phenopacketlab-backend .

      # Configure docker to use the gcloud command-line tool as a credential helper
      - run: gcloud auth configure-docker us-docker.pkg.dev
      # Push image to Google Container Registry
      - name: Image_push
        run: docker push us-docker.pkg.dev/jax-cs-registry/docker/${{ secrets.GCP_PROJECT }}/phenopacketlab-backend

      - id: 'auth'
        name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v1'
        with:
          credentials_json: ${{ secrets.GCP_CREDENTIAL }}
      # Deploy the Docker image to the Cloud run service
      - name: Deploy to Cloud Run environment
        run: |
          gcloud run deploy phenopacketlab-backend-sqa-01 --image us-docker.pkg.dev/jax-cs-registry/docker/${{ secrets.GCP_PROJECT }}/phenopacketlab-backend \
          --region us-east1 \
          --platform managed \
          --allow-unauthenticated \
          --project ${{ secrets.GCP_PROJECT }} \
          --memory 6Gi \
          --cpu 2