name: Dev Backend Deployment

on:
  push:
    branches:
      - dev

jobs:
  call-workflow-passing-data:
    uses: TheJacksonLaboratory/PhenopacketLab/.github/workflows/backend-deploy.yml@dev
    with:
      environment: dev