name: Backend SQA test Deployment

#on:
#  workflow_dispatch:
#    inputs:
#      environment:
#        description: 'Environment to deploy to'
#        required: true
#        default: 'dev'
#        type: choice
#        options:
#          - prod
#          - dev
#          - sqa
on:
  push:
    branches:
      - make_text_mining_work

env:
  PROJECT_ID: ${{ secrets.GCP_PROJECT }}

env:
  PROJECT_ID: ${{ secrets.GCP_PROJECT }}

jobs:
  deploy-backend:
    name: Setup, Build Docker Img, Publish, and Deploy to Cloud Run
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      # build backend
      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Build Backend with Maven
        run: ./mvnw -DskipTests package

      # Setup gcloud CLI
      - uses: google-github-actions/setup-gcloud@v0
        with:
          service_account_key: ${{ secrets.GOOGLE_CLOUD_SA }}
          project_id: ${{ secrets.GCP_PROJECT }}
          export_default_credentials: true

      # Configure docker to use the gcloud command-line tool as a credential helper
      - name: authenticate gcloud
        run: gcloud auth configure-docker -q

      # Download the data folder locally
      - name: Get_data
        run: gsutil cp -r gs://jax-robinson-phenopacket-project-data/data .

      # Build docker image
      - name: Image_build
        run: docker build -t us-docker.pkg.dev/jax-cs-registry/docker/$PROJECT_ID/phenopacketlab-backend-sqa-01 .

      # Configure docker to use the gcloud command-line tool as a credential helper
      - run: |
          gcloud auth configure-docker -q
      # Push image to Google Container Registry
      - name: Image_push
        run: docker push us-docker.pkg.dev/jax-cs-registry/docker/$PROJECT_ID/phenopacketlab-backend-sqa-01

      # Deploy the Docker image to the Cloud run service
      - name: Deploy
        run: |
          gcloud run deploy phenopacketlab-backend-sqa-01 --image us-docker.pkg.dev/jax-cs-registry/docker/$PROJECT_ID/phenopacketlab-backend-sqa-01 \
          --platform managed \
          --allow-unauthenticated \
          --memory 4G
