name: SQA Backend Deployment

on:
  push:
    branches:
      - sqa

jobs:
  call-workflow-passing-data:
    uses: TheJacksonLaboratory/PhenopacketLab/.github/workflows/backend-deploy.yml@sqa
    with:
      environment: sqa
    secrets:
      gcp_sa_email: ${{ secrets.GCP_SA_EMAIL }}
      gcp_credential: ${{ secrets.GCP_CREDENTIAL }}
      gcp_project: ${{ secrets.GCP_PROJECT }}