# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# It will then deploy the generated dist folder to the corresponding Google Cloud Bucket
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Dev Frontend CI/CD

on:
  push:
    branches: [ development ]

jobs:
  build-test-frontend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./phenopacketlab-frontend/
    steps:
      - uses: actions/checkout@v3

      - name: Cache node modules
        id: cache-npm
        uses: actions/cache@v3
        env:
          cache-name: cache-node-modules
        with:
          # npm cache files are stored in `~/.npm` on Linux/macOS
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - if: ${{ steps.cache-npm.outputs.cache-hit == 'false' }}
        name: List the state of node modules
        continue-on-error: true
        run: npm list

      - name: Install dependencies
        run: npm install

      - name: Build
        env:
          NODE_OPTIONS: "--max-old-space-size=4096"
        run: npm run build

      - run: sudo apt-get install xvfb
      - name: Test
        env:
          NODE_OPTIONS: "--max-old-space-size=4096"
        run: xvfb-run --auto-servernum npm test

  deploy-frontend:
    needs: [build-test-frontend]
    name: Build and Deploy Dist folder to Google Bucket
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./phenopacketlab-frontend/
    steps:
      - uses: actions/checkout@v3

      - name: Cache node modules
        id: cache-npm
        uses: actions/cache@v3
        env:
          cache-name: cache-node-modules
        with:
          # npm cache files are stored in `~/.npm` on Linux/macOS
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - if: ${{ steps.cache-npm.outputs.cache-hit == 'false' }}
        name: List the state of node modules
        continue-on-error: true
        run: npm list

      - name: Install dependencies
        run: npm install

      - name: Build
        env:
          NODE_OPTIONS: "--max-old-space-size=4096"
        run: npm run build

      # Setup gcloud CLI
      - uses: google-github-actions/setup-gcloud@v0
        with:
          service_account_email: ${{ secrets.SA_EMAIL }}
          service_account_key: ${{ secrets.GCP_CREDENTIAL }}
          project_id: ${{ secrets.GCP_PROJECT }}
          export_default_credentials: true

      - name: Deploy Dist folder to Google Bucket
        run: |
          gsutil -m -o "GSUtil:parallel_process_count=1" cp -r -z js,css ./dist/phenopacketlab-frontend/* gs://phenopacketlab-frontend-dev-01
